modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/KubeJS-Mods/KubeJS-Mekanism/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "kubejs_mekanism"
version = "${version}"
displayName = "KubeJS Mekanism"
authors = "LatvianModder"
description = '''
KubeJS Mekanism integration
'''
license = "GNU LGPLv3"

[[dependencies.kubejs_mekanism]]
modId = "kubejs"
mandatory = true
versionRange = "[1802.5.2-build.407,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.kubejs_mekanism]]
modId = "mekanism"
mandatory = true
versionRange = "[10.2.0,)"
ordering = "AFTER"
side = "BOTH"